###  Add reports

POST http://localhost:3000/reports
Content-Type: application/json

{
  "prize" : 34555,
  "make": "hundai",
  "modal": "corolla",
  "year": 2016,
  "long": 0,
  "lat": 0,
  "milage": 300
}


### Approve reports

PATCH http://localhost:3000/reports/1
Content-Type: application/json

{

}