### Signup user
POST http://localhost:3000/auth/signup
content-Type: application/json

{
  "email": "utdev31@gmail.com",
  "password": "password"
}

### Signin user
POST http://localhost:3000/auth/signin
content-Type: application/json

{
  "email": "utdev31@gmail.com",
  "password": "password"
}

### Who a m i
GET http://localhost:3000/auth/whoami


### signout  the user
POST http://localhost:3000/auth/signout

### Set color by param
GET http://localhost:3050/auth/colors/red

### Set color by param
GET http://localhost:3050/auth/colors



### Get the user with ID
GET http://localhost:3000/auth/user/1

### Get user with email
GET http://localhost:3000/auth/user?email=utdev40@gmail.com

### Update the user by id
PATCH http://localhost:3000/auth/user/1
content-Type: application/json

{
  "email": "4emailupdate@gmail.com",
  "password": "password"
}

### Delete the user with id
DELETE http://localhost:3000/auth/user/7
